chilleric/erp-os-be

README.md
=> test template

src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java, src/main/java/com/chilleric/franchise_sys/dto/user/UserResponse.java, src/main/java/com/chilleric/franchise_sys/service/user/UserServiceImpl.java
=> modify-view-side

src/main/java/com/chilleric/franchise_sys/annotation/IsObjectId.java, src/main/java/com/chilleric/franchise_sys/annotation/IsObjectIdValidator.java, src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java, src/main/java/com/chilleric/franchise_sys/controller/ShiftController.java, src/main/java/com/chilleric/franchise_sys/controller/TaskController.java, src/main/java/com/chilleric/franchise_sys/dto/shift/ShiftResponse.java, src/main/java/com/chilleric/franchise_sys/dto/task/TaskRequest.java, src/main/java/com/chilleric/franchise_sys/dto/task/TaskResponse.java, src/main/java/com/chilleric/franchise_sys/repository/informationRepository/task/StatusTask.java, src/main/java/com/chilleric/franchise_sys/repository/informationRepository/task/Task.java, src/main/java/com/chilleric/franchise_sys/repository/informationRepository/task/TaskRepository.java, src/main/java/com/chilleric/franchise_sys/repository/informationRepository/task/TaskRepositoryImpl.java, src/main/java/com/chilleric/franchise_sys/repository/informationRepository/task/TaskStatus.java, src/main/java/com/chilleric/franchise_sys/service/task/TaskService.java, src/main/java/com/chilleric/franchise_sys/service/task/TaskServiceImpl.java
Implement Task features: controller + service + repository
=> 42 implement task

src/main/java/com/chilleric/franchise_sys/dto/bill/BillRequest.java, src/main/java/com/chilleric/franchise_sys/dto/bill/BillResponse.java, src/main/java/com/chilleric/franchise_sys/repository/crmRepository/bill/Bill.java, src/main/java/com/chilleric/franchise_sys/service/bill/BillResponseServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/bill/BillService.java, src/main/java/com/chilleric/franchise_sys/service/bill/BillServiceImpl.java
-Update workflow in Bill: `create` and `update`
=> 61 bill service update completed workflow

src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java, src/main/java/com/chilleric/franchise_sys/controller/PathController.java, src/main/java/com/chilleric/franchise_sys/dto/path/PathRequest.java, src/main/java/com/chilleric/franchise_sys/dto/path/PathResponse.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/path/Path.java, src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> update: add  icon in Path

src/main/java/com/chilleric/franchise_sys/annotation/IsBase64/IsBase64.java, src/main/java/com/chilleric/franchise_sys/annotation/IsBase64/IsBase64Validator.java, src/main/java/com/chilleric/franchise_sys/annotation/IsObjectId/IsObjectId.java, src/main/java/com/chilleric/franchise_sys/annotation/IsObjectId/IsObjectIdValidator.java, src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java, src/main/java/com/chilleric/franchise_sys/dto/path/PathRequest.java, src/main/java/com/chilleric/franchise_sys/dto/task/TaskRequest.java, src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> add path validation

src/main/java/com/chilleric/franchise_sys/service/navbar/NavbarServiceImpl.java
=> fix response

src/main/java/com/chilleric/franchise_sys/service/navbar/NavbarServiceImpl.java
=> fix sidebar resposne

src/main/java/com/chilleric/franchise_sys/config/EndpointsListener.java, src/main/java/com/chilleric/franchise_sys/dto/navbar/ContentNavbarRequest.java, src/main/java/com/chilleric/franchise_sys/dto/navbar/ContentNavbarResponse.java, src/main/java/com/chilleric/franchise_sys/dto/navbar/NavbarRequest.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/navbar/ContentNavbar.java, src/main/java/com/chilleric/franchise_sys/service/navbar/NavbarServiceImpl.java
=> edit dto, dao nacbar

src/main/java/com/chilleric/franchise_sys/config/EndpointsListener.java, src/main/java/com/chilleric/franchise_sys/controller/NavbarController.java, src/main/java/com/chilleric/franchise_sys/dto/path/PathRequest.java, src/main/java/com/chilleric/franchise_sys/dto/path/PathResponse.java, src/main/java/com/chilleric/franchise_sys/dto/permission/PermissionRequest.java, src/main/java/com/chilleric/franchise_sys/dto/permission/PermissionResponse.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/path/Path.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/permission/Permission.java, src/main/java/com/chilleric/franchise_sys/service/navbar/NavbarService.java, src/main/java/com/chilleric/franchise_sys/service/navbar/NavbarServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java
=> Add endpoint permission

src/main/java/com/chilleric/franchise_sys/config/EndpointsListener.java, src/main/java/com/chilleric/franchise_sys/dto/navbar/NavbarRequest.java, src/main/java/com/chilleric/franchise_sys/dto/navbar/NavbarResponse.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/navbar/Navbar.java, src/main/java/com/chilleric/franchise_sys/service/navbar/NavbarServiceImpl.java
=> discard userid navbar

src/main/java/com/chilleric/franchise_sys/config/EndpointsListener.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/permission/Permission.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java
=> discard path from permission

src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java, src/main/java/com/chilleric/franchise_sys/controller/TableController.java
=> add endpoint tableignore

src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java, src/main/java/com/chilleric/franchise_sys/controller/TableController.java
=> modify logic response

src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java
=> fix userlist permission

src/main/java/com/chilleric/franchise_sys/dto/user/UserResponse.java
=> change user response field

src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java
=> discard checkpath

src/main/java/com/chilleric/franchise_sys/config/EndpointsListener.java, src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java, src/main/java/com/chilleric/franchise_sys/controller/AccessabilityController.java, src/main/java/com/chilleric/franchise_sys/controller/NavbarController.java, src/main/java/com/chilleric/franchise_sys/controller/PathController.java, src/main/java/com/chilleric/franchise_sys/controller/PermissionController.java, src/main/java/com/chilleric/franchise_sys/controller/UserController.java, src/main/java/com/chilleric/franchise_sys/dto/common/ValidationResult.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/accessability/Accessability.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/permission/Permission.java, src/main/java/com/chilleric/franchise_sys/service/accessability/AccessabilityService.java, src/main/java/com/chilleric/franchise_sys/service/accessability/AccessabilityServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/navbar/NavbarService.java, src/main/java/com/chilleric/franchise_sys/service/navbar/NavbarServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/path/PathService.java, src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionService.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/user/UserService.java, src/main/java/com/chilleric/franchise_sys/service/user/UserServiceImpl.java
=> add serverside for access and perm

src/main/java/com/chilleric/franchise_sys/controller/PermissionController.java, src/main/java/com/chilleric/franchise_sys/controller/UserController.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionService.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/user/UserService.java, src/main/java/com/chilleric/franchise_sys/service/user/UserServiceImpl.java
=> add filter for getlist user and perm

src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java
=> change condition modify position

src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java, src/main/java/com/chilleric/franchise_sys/controller/PermissionController.java, src/main/java/com/chilleric/franchise_sys/dto/permission/PermissionRequest.java, src/main/java/com/chilleric/franchise_sys/service/login/LoginServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionService.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java
=> Modify logic access and perm

src/main/java/com/chilleric/franchise_sys/dto/permission/PermissionResponse.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java
=> add isServer to perm response

src/main/java/com/chilleric/franchise_sys/dto/permission/PermissionResponse.java, src/main/java/com/chilleric/franchise_sys/service/permission/PermissionServiceImpl.java
=> fix select is server

src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java, src/main/java/com/chilleric/franchise_sys/controller/PermissionController.java
=> Modify logical permission

src/main/java/com/chilleric/franchise_sys/dto/path/PathResponse.java
=> disacrd s from path

src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> add logic path sure admin

src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java, src/main/java/com/chilleric/franchise_sys/controller/PathController.java, src/main/java/com/chilleric/franchise_sys/service/path/PathService.java, src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> add path update

src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> fix condition validate path update

src/main/java/com/chilleric/franchise_sys/constant/LanguageMessageKey.java, src/main/java/com/chilleric/franchise_sys/controller/SettingsController.java, src/main/java/com/chilleric/franchise_sys/dto/settings/AvatarRequest.java, src/main/java/com/chilleric/franchise_sys/service/settings/SettingService.java, src/main/java/com/chilleric/franchise_sys/service/settings/SettingServiceImpl.java
=> hotfix avt

src/main/java/com/chilleric/franchise_sys/controller/SettingsController.java, src/main/java/com/chilleric/franchise_sys/dto/user/UserResponse.java, src/main/java/com/chilleric/franchise_sys/service/user/UserServiceImpl.java
=> change position avt in response

src/main/java/com/chilleric/franchise_sys/service/login/LoginServiceImpl.java
=> fix verify email

src/main/java/com/chilleric/franchise_sys/config/EndpointsListener.java, src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java, src/main/java/com/chilleric/franchise_sys/controller/LoginController.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/user/User.java, src/main/java/com/chilleric/franchise_sys/service/login/LoginService.java, src/main/java/com/chilleric/franchise_sys/service/login/LoginServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/user/UserServiceImpl.java
=> Update multiple device

src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java
=> fix validation bug

Dockerfile, src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java
=> add docker file

.github/workflows/ci-cd.yml, src/main/java/com/chilleric/franchise_sys/pusher/PusherServiceImpl.java, src/main/resources/application.properties
=> add var to deep link

src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> fixbug-update path

src/main/java/com/chilleric/franchise_sys/controller/TableController.java, src/main/java/com/chilleric/franchise_sys/pusher/PusherServiceImpl.java
=> get table fix

src/main/java/com/chilleric/franchise_sys/service/login/LoginServiceImpl.java
=> fix tokens list out of bound

src/main/java/com/chilleric/franchise_sys/controller/UserController.java
=> show editable

src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> fix check userid in path

src/main/java/com/chilleric/franchise_sys/config/EndpointsListener.java, src/main/java/com/chilleric/franchise_sys/controller/AbstractController.java, src/main/java/com/chilleric/franchise_sys/controller/UserController.java, src/main/java/com/chilleric/franchise_sys/dto/user/UserNotificationResponse.java, src/main/java/com/chilleric/franchise_sys/pusher/PusherServiceImpl.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/user/User.java, src/main/java/com/chilleric/franchise_sys/repository/systemRepository/user/UserNotification.java, src/main/java/com/chilleric/franchise_sys/service/login/LoginServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/user/UserService.java, src/main/java/com/chilleric/franchise_sys/service/user/UserServiceImpl.java
=> 115 implement notifications

src/main/java/com/chilleric/franchise_sys/pusher/PusherUpdateResponse.java, src/main/java/com/chilleric/franchise_sys/service/login/LoginServiceImpl.java, src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> push update noti

src/main/java/com/chilleric/franchise_sys/service/path/PathServiceImpl.java
=> change message
